name: ${project.name}
version: ${buildNumber}
description: ${project.description}
author: ${project.organization.name}
website: ${project.organization.url}

main: com.almuramc.portables.bukkit.PortablesPlugin
depend: [Vault]
softdepend: [Spout]
load: POSTWORLD

commands:
    portables:
        description: Manage Portables
        usage: /portables [command] [arguments]
permissions:
    portables.reload:
        description: Allows the user to reload Portables
        default: op
    portables.enchant.cost:
        description: Will users get charged for opening the enchantment table
        default: false
    portables.enchant.has:
        description: Users have to have an enchantment table in their inventory to access portable mode
        default: false
    portables.enchant.use:
        description: Allows users to access the portable enchantment table.
        default: op
    portables.workbench.cost:
        description: Will users get charged for opening the workbench
        default: false
    portables.workbench.has:
        description: Users have to have a workbench in their inventory to access portable mode
        default: false
    portables.workbench.use:
        description: Allows users to access the portable workbench.
        default: op