name: ${project.name}
version: ${buildNumber}
description: ${project.description}
author: ${project.organization.name}
website: ${project.organization.url}

main: com.almuramc.portables.bukkit.PortablesPlugin
softdepend: [Spout]
load: POSTWORLD

commands:
    workbench:
        description: Manage Portables
        usage: /portables [command] [arguments]
permissions:
    portables.brewingstand.cost:
        description: Allows users to access the portable workbench.
        default: op
    portables.brewsingstand.use:
        description: Allows users to access the portable workbench.
        default: op
    portables.furnace.cost:
        description: Allows users to access the portable workbench.
        default: op
    portables.furnace.use:
        description: Allows users to access the portable workbench.
        default: op
    portables.workbench.cost:
        description: Allows users to access the portable workbench.
        default: op
    portables.workbench.use:
        description: Allows users to access the portable workbench.
        default: op